In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
# Q1. Ans. : 
arr1[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
# Q2. Ans. :
arr1[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[ 168, 1441, 7757, 8072, 6038],
       [5478, 3906, 4701,  938, 3506]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
np.percentile(arr1,25)

9.75

In [0]:
# Q3. Ans. :

# Method 1: L2 normalization
norm_arr = arr2/np.linalg.norm(arr2,axis=-1)[:, np.newaxis]
norm_arr

array([[0.01312298, 0.11256082, 0.60592247, 0.63052806, 0.47164624],
       [0.61041526, 0.4352468 , 0.5238339 , 0.10452163, 0.39067468]])

In [0]:
# Verifying
np.sum(norm_arr**2,axis=-1)          # Sum of squares of values of each row must be 1

array([1., 1.])

In [0]:
# Method 2: L1 normalization
from sklearn.preprocessing import normalize

norm_arr2 = normalize(arr2,axis=1,norm='l1')
norm_arr2

array([[0.00715624, 0.06138184, 0.33042256, 0.34384052, 0.25719884],
       [0.29564467, 0.21080468, 0.2537104 , 0.05062335, 0.1892169 ]])

In [0]:
# Verifying
np.sum(norm_arr2,axis=-1)            # Sum of rows must be 1

array([1., 1.])

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
# Q4. Ans. :

# 1. Running with arr1
np.isnan(arr1)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [0]:
# Q4. Ans. :

# 2. Working on a new array
arr_test = [[1,2,np.nan,3,4],
            [np.nan,7,np.nan,np.nan,1]]
np.isnan(arr_test)

array([[False, False,  True, False, False],
       [ True, False,  True,  True, False]])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
# Q5. Ans. :

# The function definition
def nth_largest(arr,n):
  if n <= len(arr):
    return np.sort(arr)[-n]
  else:
    return "n is greater than size of array."


# Testing the function
# 1.
a = np.array([12,34,40,7,1,0])
n = 3
print("Case 1: for n = 3 -->",nth_largest(a,n))

# 2.
b = np.array([12,34,40,7,1,0])
n = 1
print("Case 2: for n = 1 -->",nth_largest(a,n))

# 3. Checking the faulty condition, n > len(arr)
c =  np.array([12,34,40,7,1,0])
n = 7
print("Case 3: for n = 7 -->",nth_largest(a,n))

Case 1: for n = 3 --> 12
Case 2: for n = 1 --> 40
Case 3: for n = 7 --> n is greater than size of array.
